(function($){$.fn.jRating=function(op){var defaults={bigStarsPath:'includes/jrating/icons/stars.png',smallStarsPath:'includes/jrating/icons/small.png',likesPath:'includes/jrating/icons/like_dislike.png',pn_icon_Path:'includes/jrating/icons/pn_icon.png',bigstarWidth:23,bigstarHeight:20,smallstarWidth:12,smallstarHeight:10,likesWidth:20,likesHeight:20,pnWidth:24,pnHeight:20,phpPath:'index.php',type:'big',step:!1,isDisabled:!1,showRateInfo:!0,canRateAgain:!1,sendRequest:!0,length:5,decimalLength:0,rateMax:20,rateInfosX:-45,rateInfosY:5,likesboxwidth:100,likesboxheight:20,pnboxwidth:100,pnboxheight:20,nbRates:1,onSuccess:null,onError:null,onClick:null};if(this.length>0)
return this.each(function(){var opts=$.extend(defaults,op),newWidth=0,starWidth=0,starHeight=0,bgPath='',hasRated=!1,globalWidth=0,nbOfRates=opts.nbRates;if($(this).hasClass('jDisabled')||opts.isDisabled)
var jDisabled=!0;else var jDisabled=!1;getStarWidth();$(this).height(starHeight);var average=parseFloat($(this).attr('data-average')),idBox=parseInt($(this).attr('data-id')),old_score=parseInt($(this).attr('data-score')),old_rate=parseInt($(this).attr('data-ratings')),db_table=$(this).attr('data-db-table'),db_table_var=$(this).attr('data-db-table-var'),c_votetype=$(this).attr('data-c-votetype'),likesrate=$(this).attr('data-likesrate'),widthRatingContainer=starWidth*opts.length;if(c_votetype==1)
{widthColor=average/opts.rateMax*widthRatingContainer,quotient=$('<div>',{'class':'jRatingColor',css:{width:widthColor}}).appendTo($(this)),average=$('<div>',{'class':'jRatingAverage',css:{width:0,top:-starHeight}}).appendTo($(this)),jstar=$('<div>',{'class':'jStar',css:{width:widthRatingContainer,height:starHeight,top:-(starHeight*2),background:'url('+opts.bigStarsPath+') repeat-x'}}).appendTo($(this));$(this).css({width:widthRatingContainer,overflow:'hidden',zIndex:1,position:'relative'});if(!jDisabled)
$(this).unbind().bind({mouseenter:function(e){var realOffsetLeft=findRealLeft(this);var relativeX=e.pageX-realOffsetLeft;if(opts.showRateInfo)
var tooltip=$('<p>',{'class':'jRatingInfos',html:getNote(relativeX)+' <span class="maxRate">/ '+opts.rateMax+'</span>',css:{top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}}).appendTo('body').show()},mouseover:function(e){$(this).css('cursor','pointer')},mouseout:function(){$(this).css('cursor','default');if(hasRated)average.width(globalWidth);else average.width(0)},mousemove:function(e){var realOffsetLeft=findRealLeft(this);var relativeX=e.pageX-realOffsetLeft;if(opts.step)newWidth=Math.floor(relativeX/starWidth)*starWidth+starWidth;else newWidth=relativeX;average.width(newWidth);if(opts.showRateInfo)
$("p.jRatingInfos").css({top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}).html(getNote(newWidth)+' <span class="maxRate">/ '+opts.rateMax+'</span><br /><span dir="rtl">'+$(this).attr('data-score')+' امیاز از '+$(this).attr('data-ratings')+' رأی</span>')},mouseleave:function(){$("p.jRatingInfos").remove()},click:function(e){var element=this;hasRated=!0;globalWidth=newWidth;nbOfRates--;if(!opts.canRateAgain||parseInt(nbOfRates)<=0)$(this).unbind().css('cursor','default').addClass('jDisabled');if(opts.showRateInfo)$("p.jRatingInfos").fadeOut('fast',function(){$(this).remove()});e.preventDefault();var rate=getNote(newWidth);average.width(newWidth);$('.datasSent p').html('<strong>idBox : </strong>'+idBox+'<br /><strong>rate : </strong>'+rate+'<br /><strong>action :</strong> rating');$('.serverResponse p').html('<strong>Loading...</strong>');if(opts.onClick)opts.onClick(element,rate);if(opts.sendRequest){$.post(opts.phpPath,{idBox:idBox,rate:rate,old_rate:old_rate,old_score:old_score,db_table:db_table,db_table_var:db_table_var,c_votetype:c_votetype,jaction:'rating',csrf_token:pn_csrf_token},function(data){alert(data.message);if(!data.error)
{}
else{}},'json')}}});else $(this).unbind().bind({mouseenter:function(e){if(opts.showRateInfo)
var tooltip=$('<p>',{'class':'jRatingInfos',html:'<span class="rateinfo">'+$(this).attr('data-score')+' امیاز از '+$(this).attr('data-ratings')+' رأی</span>',css:{top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}}).appendTo('body').show()},mousemove:function(e){if(opts.showRateInfo)
$("p.jRatingInfos").css({top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}).html('<span class="rateinfo">'+$(this).attr('data-score')+' امیاز از '+$(this).attr('data-ratings')+' رأی</span>')},mouseleave:function(){$("p.jRatingInfos").remove()}})}
else{var old_likesrate=likesrate.split(',');var old_pn_rate=old_likesrate[0]-old_likesrate[1];var old_pn_rate_color=(old_pn_rate>=0)?"#236316":"#ff0000";if(c_votetype==2)
{var jPnrate = opts.pnrate_theme.replace(/{IDBOX}/g, idBox).replace(/{AJAX-LOADER-IMG-PATH}/g, phpnuke_cdnurl + 'images/ajax-loader.gif').replace(/{OLD_PNRATE_COLOR}/g, old_pn_rate_color).replace(/{OLD_PNRATE}/g, old_pn_rate);pnratediv=$(jPnrate).appendTo($(this));$(this).css({width:opts.pnboxwidth,height:opts.pnboxheight,overflow:'hidden',zIndex:1,position:'relative'});var pn_loading_pos=opts.pnWidth*2;$("#like-loading-"+idBox).css({'left':pn_loading_pos+'px'});$(".positive-rate, .negative-rate").css({'width':opts.pnWidth+'px','height':opts.pnHeight+'px'});$(".pnrate-count").css({'width':(opts.pnboxwidth-(opts.pnWidth*2))+'px'})}
else{var jLike=opts.like_theme.replace(/{IDBOX}/g, idBox).replace(/{AJAX-LOADER-IMG-PATH}/g, phpnuke_cdnurl+'images/ajax-loader.gif').replace(/{DISLIKE-COUNT}/g, old_likesrate[1]).replace(/{LIKE-COUNT}/g, old_likesrate[0]);likediv=$(jLike).appendTo($(this));$(this).css({width:opts.likesboxwidth,height:opts.likesboxheight,overflow:'hidden',zIndex:1,position:'relative'});var like_loading_pos=opts.likesWidth*2;$("#like-loading-"+idBox).css({'left':like_loading_pos+'px'});$(".like, .dislike").css({'width':opts.likesWidth+'px','height':opts.likesHeight+'px'})}
if(!jDisabled)
$(this).unbind().bind({mouseenter:function(e){$(this).find(((c_votetype==2)?'.positive-rate':'.like')).attr('onclick','update_likes(\''+idBox+'\',\'1\');');$(this).find(((c_votetype==2)?'.negative-rate':'.dislike')).attr('onclick','update_likes(\''+idBox+'\',\'-1\');');if(opts.showRateInfo)
var tooltip=$('<p>',{'class':'jRatingInfos',html:('<span class="rateinfo">'+$(this).attr('data-ratings')+' رأی</span>'),css:{top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}}).appendTo('body').show()},mousemove:function(e){if(opts.showRateInfo)
$("p.jRatingInfos").css({top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}).html('<span class="rateinfo">'+$(this).attr('data-ratings')+' رأی</span>')},mouseleave:function(){$("p.jRatingInfos").remove()},click:function(e){var element=this;var rate=(e.target.className.match(/dislike/g)||e.target.className=='negative-rate')?(-1):1;hasRated=!0;nbOfRates--;if(!opts.canRateAgain||parseInt(nbOfRates)<=0)$(this).unbind().css('cursor','default').addClass('jDisabled');if(opts.showRateInfo)$("p.jRatingInfos").fadeOut('fast',function(){$(this).remove()});e.preventDefault();if(opts.onClick)opts.onClick(element,rate);$("#like-loading-"+idBox).css({'display':'block'});if(opts.sendRequest){$.post(opts.phpPath,{idBox:idBox,rate:rate,oldlikesrate:likesrate,db_table:db_table,db_table_var:db_table_var,c_votetype:c_votetype,jaction:'liking',csrf_token:pn_csrf_token},function(data){alert(data.message);if(!data.error)
{response=data.server.split(",");if(c_votetype==2)
{new_Rate=parseInt(response[0]-response[1]);$("#pnrate-count-"+idBox).html(new_Rate);$("#pnrate-count-"+idBox).css({'color':((new_Rate>=0)?'#236316':'#ff0000')});$("#like-loading-"+idBox).css({'display':'none'});$(this).find('.positive-rate').removeAttr("onclick");$(this).find('.negative-rate').removeAttr("onclick")}
else{$("#like-count-"+idBox).html(response[0]);$("#dislike-count-"+idBox).html(response[1]);$("#like-loading-"+idBox).css({'display':'none'});$(this).find('.like').removeAttr("onclick");$(this).find('.dislike').removeAttr("onclick")}}
else{}},'json')}}});else $(this).unbind().bind({mouseenter:function(e){if(opts.showRateInfo)
var tooltip=$('<p>',{'class':'jRatingInfos',html:('<span class="rateinfo">'+$(this).attr('data-ratings')+' رأی</span>'),css:{top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}}).appendTo('body').show()},mousemove:function(e){if(opts.showRateInfo)
$("p.jRatingInfos").css({top:(e.pageY+opts.rateInfosY),left:(e.pageX+opts.rateInfosX)}).html('<span class="rateinfo">'+$(this).attr('data-ratings')+' رأی</span>')},mouseleave:function(){$("p.jRatingInfos").remove()},click:function(e){alert('شما قبلاً رأی داده اید')}})}
function getNote(relativeX){var noteBrut=parseFloat((relativeX*100/widthRatingContainer)*parseInt(opts.rateMax)/100);var dec=Math.pow(10,parseInt(opts.decimalLength));var note=Math.round(noteBrut*dec)/dec;return note};function getStarWidth(){switch(opts.type){case'small':starWidth=opts.smallstarWidth;starHeight=opts.smallstarHeight;bgPath=opts.smallStarsPath;break;default:starWidth=opts.bigstarWidth;starHeight=opts.bigstarHeight;bgPath=opts.bigStarsPath}};function findRealLeft(obj){if(!obj)return 0;return obj.offsetLeft+findRealLeft(obj.offsetParent)}})}})(jQuery)