services:
    gfksx.ListSubforumsInColumns.listener:
        class: gfksx\ListSubforumsInColumns\event\listener
        arguments:
            - '@user'
            - '@request'
            - '@template'
        tags:
            - { name: event.listener }
