/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.dialog.add("specialchar",function(h){var e,n=h.lang.specialchar,m=function(c){var a;c=c.data?c.data.getTarget():new CKEDITOR.dom.element(c);"a"==c.getName()&&(a=c.getChild(0).getHtml())&&(c.removeClass("cke_light_background"),e.hide(),"source"==h.mode?MyBBEditor.insertText(a,"",h.name+"_2"):(c=h.document.createElement("span"),c.setHtml(a),h.insertText(c.getText())))},p=CKEDITOR.tools.addFunction(m),l,g=function(c,a){var b;a=a||c.data.getTarget();"span"==a.getName()&&(a=a.getParent());if("a"==
a.getName()&&(b=a.getChild(0).getHtml())){l&&d(null,l);var f=e.getContentElement("info","htmlPreview").getElement();e.getContentElement("info","charPreview").getElement().setHtml(b);f.setHtml(CKEDITOR.tools.htmlEncode(b));a.getParent().addClass("cke_light_background");l=a}},d=function(c,a){a=a||c.data.getTarget();"span"==a.getName()&&(a=a.getParent());"a"==a.getName()&&(e.getContentElement("info","charPreview").getElement().setHtml("\x26nbsp;"),e.getContentElement("info","htmlPreview").getElement().setHtml("\x26nbsp;"),
a.getParent().removeClass("cke_light_background"),l=void 0)},q=CKEDITOR.tools.addFunction(function(c){c=new CKEDITOR.dom.event(c);var a=c.getTarget(),b;b=c.getKeystroke();var f="rtl"==h.lang.dir;switch(b){case 38:if(b=a.getParent().getParent().getPrevious())b=b.getChild([a.getParent().getIndex(),0]),b.focus(),d(null,a),g(null,b);c.preventDefault();break;case 40:(b=a.getParent().getParent().getNext())&&(b=b.getChild([a.getParent().getIndex(),0]))&&1==b.type&&(b.focus(),d(null,a),g(null,b));c.preventDefault();
break;case 32:m({data:c});c.preventDefault();break;case f?37:39:if(b=a.getParent().getNext())b=b.getChild(0),1==b.type?(b.focus(),d(null,a),g(null,b),c.preventDefault(!0)):d(null,a);else if(b=a.getParent().getParent().getNext())(b=b.getChild([0,0]))&&1==b.type?(b.focus(),d(null,a),g(null,b),c.preventDefault(!0)):d(null,a);break;case f?39:37:(b=a.getParent().getPrevious())?(b=b.getChild(0),b.focus(),d(null,a),g(null,b),c.preventDefault(!0)):(b=a.getParent().getParent().getPrevious())?(b=b.getLast().getChild(0),
b.focus(),d(null,a),g(null,b),c.preventDefault(!0)):d(null,a)}});return{title:n.title,minWidth:430,minHeight:280,buttons:[CKEDITOR.dialog.cancelButton],charColumns:17,onLoad:function(){for(var c=this.definition.charColumns,a=h.config.specialChars,b=CKEDITOR.tools.getNextId()+"_specialchar_table_label",f=['\x3ctable role\x3d"listbox" aria-labelledby\x3d"'+b+'" style\x3d"width: 320px; height: 100%; border-collapse: separate;" align\x3d"center" cellspacing\x3d"2" cellpadding\x3d"2" border\x3d"0"\x3e'],
d=0,g=a.length,k,e;d<g;){f.push('\x3ctr role\x3d"presentation"\x3e');for(var l=0;l<c;l++,d++){if(k=a[d]){k instanceof Array?(e=k[1],k=k[0]):(e=k.replace("\x26","").replace(";","").replace("#",""),e=n[e]||k);var m="cke_specialchar_label_"+d+"_"+CKEDITOR.tools.getNextNumber();f.push('\x3ctd class\x3d"cke_dark_background" style\x3d"cursor: default" role\x3d"presentation"\x3e\x3ca href\x3d"javascript: void(0);" role\x3d"option" aria-posinset\x3d"'+(d+1)+'"',' aria-setsize\x3d"'+g+'"',' aria-labelledby\x3d"'+
m+'"',' class\x3d"cke_specialchar" title\x3d"',CKEDITOR.tools.htmlEncode(e),'" onkeydown\x3d"CKEDITOR.tools.callFunction( '+q+', event, this )" onclick\x3d"CKEDITOR.tools.callFunction('+p+', this); return false;" tabindex\x3d"-1"\x3e\x3cspan style\x3d"margin: 0 auto;cursor: inherit"\x3e'+k+'\x3c/span\x3e\x3cspan class\x3d"cke_voice_label" id\x3d"'+m+'"\x3e'+e+"\x3c/span\x3e\x3c/a\x3e")}else f.push('\x3ctd class\x3d"cke_dark_background"\x3e\x26nbsp;');f.push("\x3c/td\x3e")}f.push("\x3c/tr\x3e")}f.push("\x3c/tbody\x3e\x3c/table\x3e",
'\x3cspan id\x3d"'+b+'" class\x3d"cke_voice_label"\x3e'+n.options+"\x3c/span\x3e");this.getContentElement("info","charContainer").getElement().setHtml(f.join(""))},contents:[{id:"info",label:h.lang.common.generalTab,title:h.lang.common.generalTab,padding:0,align:"top",elements:[{type:"hbox",align:"top",widths:["320px","90px"],children:[{type:"html",id:"charContainer",html:"",onMouseover:g,onMouseout:d,focus:function(){var c=this.getElement().getElementsByTag("a").getItem(0);setTimeout(function(){c.focus();
g(null,c)},0)},onShow:function(){var c=this.getElement().getChild([0,0,0,0,0]);setTimeout(function(){c.focus();g(null,c)},0)},onLoad:function(c){e=c.sender}},{type:"hbox",align:"top",widths:["100%"],children:[{type:"vbox",align:"top",children:[{type:"html",html:"\x3cdiv\x3e\x3c/div\x3e"},{type:"html",id:"charPreview",className:"cke_dark_background",style:"border:1px solid #eeeeee;font-size:28px;height:40px;width:70px;padding-top:9px;font-family:'Microsoft Sans Serif',Arial,Helvetica,Verdana;text-align:center;",
html:"\x3cdiv\x3e\x26nbsp;\x3c/div\x3e"},{type:"html",id:"htmlPreview",className:"cke_dark_background",style:"border:1px solid #eeeeee;font-size:14px;height:20px;width:70px;padding-top:2px;font-family:'Microsoft Sans Serif',Arial,Helvetica,Verdana;text-align:center;",html:"\x3cdiv\x3e\x26nbsp;\x3c/div\x3e"}]}]}]}]}]}});