services:
    shredder.sitemap.appender:
        class: shredder\sitemap\appender
        arguments:
            - '@config'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    shredder.sitemap.core:
        class: shredder\sitemap\core
        arguments:
            - '@shredder.sitemap.appender'
            - '@auth'
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@service_container'
            - '@ext.manager'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    shredder.sitemap.controller:
        class: shredder\sitemap\controller\sitemap
        arguments:
            - '@shredder.sitemap.appender'
            - '@shredder.sitemap.core'
            - '@cache'
            - '@config'
            - '@user'
    shredder.sitemap.listener:
        class: shredder\sitemap\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
