var chart;function main_chart(chart_id,chart_data){chart=AmCharts.makeChart(chart_id,{"type":"serial","categoryField":"date","fontFamily":"Tahoma","marginRight":20,"marginLeft":0,"autoMarginOffset":0,"mouseWheelZoomEnabled":!0,"addClassNames":!0,"colors":["#356e8c","#8c7335",],"categoryAxis":{"gridPosition":"start","autoGridCount":!1,"labelRotation":90,"listeners":[{"event":"clickItem","method":function(event){if(event.serialDataItem.dataContext.url!==undefined)
window.location.href=event.serialDataItem.dataContext.url}}]},"chartCursor":{"enabled":!0,"cursorPosition":"mouse","showNextAvailable":!0,"cursorColor":"#888888"},"export":{"enabled":!0},"chartScrollbar":{"enabled":!0},"trendLines":[],"graphs":[{"bullet":"round","hideBulletsCount":60,"id":"AmGraph-1","title":"آمار بازديد","valueField":"c-1","balloonText":"<span style='font-size:15px;'>[[value]]</span>"},{"bullet":"square","hideBulletsCount":60,"id":"AmGraph-2","title":"ورودي آي پي","valueField":"c-2","balloonText":"<span style='font-size:15px;'>[[value]]</span>"}],"balloon":{"borderThickness":1,"shadowAlpha":0},"guides":[],"valueAxes":[{"id":"ValueAxis-1","title":"تعداد"}],"allLabels":[],"legend":{"enabled":!0,"useGraphSettings":!0},"responsive":{"enabled":!0},"dataProvider":chart_data,"listeners":[{"event":"init","method":function(event){var chart=event.chart;for(var x=0;x<chart.graphs.length;x++){var graph=chart.graphs[x];var graphSum=0;for(var i=0;i<chart.dataProvider.length;i++){graphSum+=chart.dataProvider[i][graph.valueField]}
if(graphSum==0)
{graph.visibleInLegend=!1;chart.hideGraph(graph)}}}}]});chart.addListener("rendered",zoomChart);zoomChart()}
function yearly_chart(chart_id,chart_data){chart=AmCharts.makeChart(chart_id,{"type":"serial","categoryField":"date","fontFamily":"Tahoma","marginRight":20,"marginLeft":0,"autoMarginOffset":0,"mouseWheelZoomEnabled":!0,"addClassNames":!0,"colors":["#356e8c","#8c7335",],"categoryAxis":{"gridPosition":"start","autoGridCount":!1,"labelRotation":90,"listeners":[{"event":"clickItem","method":function(event){if(event.serialDataItem.dataContext.url!==undefined)
window.location.href=event.serialDataItem.dataContext.url}}]},"chartCursor":{"enabled":!0,"cursorPosition":"mouse","showNextAvailable":!0,"cursorColor":"#888888"},"export":{"enabled":!0},"chartScrollbar":{"enabled":!0},"trendLines":[],"graphs":[{"bullet":"round","hideBulletsCount":60,"id":"yearlyAmGraph-1","title":"آمار بازديد","valueField":"c-1","type":"smoothedLine","balloonText":"<span style='font-size:15px;'>[[value]]</span>"},{"bullet":"square","hideBulletsCount":60,"id":"yearlyAmGraph-2","title":"ورودي آي پي","valueField":"c-2","type":"smoothedLine","balloonText":"<span style='font-size:15px;'>[[value]]</span>"}],"balloon":{"borderThickness":1,"shadowAlpha":0},"guides":[],"valueAxes":[{"id":"yearlyValueAxis-1","title":"تعداد"}],"allLabels":[],"legend":{"enabled":!0,"useGraphSettings":!0},"responsive":{"enabled":!0},"dataProvider":chart_data,"listeners":[{"event":"init","method":function(event){var chart=event.chart;for(var x=0;x<chart.graphs.length;x++){var graph=chart.graphs[x];var graphSum=0;for(var i=0;i<chart.dataProvider.length;i++){graphSum+=chart.dataProvider[i][graph.valueField]}
if(graphSum==0)
{graph.visibleInLegend=!1;chart.hideGraph(graph)}}}}]});chart.addListener("rendered",zoomChart);zoomChart()}
function monthly_chart(chart_id,chart_data){chart=AmCharts.makeChart(chart_id,{"type":"serial","categoryField":"date","fontFamily":"Tahoma","marginRight":20,"marginLeft":0,"autoMarginOffset":0,"mouseWheelZoomEnabled":!0,"addClassNames":!0,"colors":["#356e8c","#8c7335",],"categoryAxis":{"gridPosition":"start","autoGridCount":!1,"labelRotation":90,"listeners":[{"event":"clickItem","method":function(event){if(event.serialDataItem.dataContext.url!==undefined)
window.location.href=event.serialDataItem.dataContext.url}}]},"chartCursor":{"enabled":!0,"cursorPosition":"mouse","showNextAvailable":!0,"cursorColor":"#888888"},"export":{"enabled":!0},"chartScrollbar":{"enabled":!0},"trendLines":[],"graphs":[{"bullet":"round","hideBulletsCount":60,"id":"monthlyAmGraph-1","title":"آمار بازديد","valueField":"c-1","type":"smoothedLine","balloonText":"<span style='font-size:15px;'>[[value]]</span>"},{"bullet":"square","hideBulletsCount":60,"id":"monthlyAmGraph-2","title":"ورودي آي پي","valueField":"c-2","type":"smoothedLine","balloonText":"<span style='font-size:15px;'>[[value]]</span>"}],"balloon":{"borderThickness":1,"shadowAlpha":0},"guides":[],"valueAxes":[{"id":"monthlyValueAxis-1","title":"تعداد"}],"allLabels":[],"legend":{"enabled":!0,"useGraphSettings":!0},"responsive":{"enabled":!0},"dataProvider":chart_data,"listeners":[{"event":"init","method":function(event){var chart=event.chart;for(var x=0;x<chart.graphs.length;x++){var graph=chart.graphs[x];var graphSum=0;for(var i=0;i<chart.dataProvider.length;i++){graphSum+=chart.dataProvider[i][graph.valueField]}
if(graphSum==0)
{graph.visibleInLegend=!1;chart.hideGraph(graph)}}}}]});chart.addListener("rendered",zoomChart);zoomChart()}
function daily_chart(chart_id,chart_data){chart=AmCharts.makeChart(chart_id,{"type":"serial","categoryField":"date","startDuration":1,"fontFamily":"Tahoma","marginRight":20,"marginLeft":0,"autoMarginOffset":0,"mouseWheelZoomEnabled":!0,"addClassNames":!0,"categoryAxis":{"autoRotateAngle":0,"autoRotateCount":0,"autoGridCount":!1,"gridPosition":"start","minHorizontalGap":72,"listeners":[{"event":"clickItem","method":function(event){if(event.serialDataItem.dataContext.url!==undefined)
window.location.href=event.serialDataItem.dataContext.url}}]},"chartCursor":{"enabled":!0,"cursorPosition":"mouse","showNextAvailable":!0,"cursorColor":"#888888"},"export":{"enabled":!0},"chartScrollbar":{"enabled":!0},"trendLines":[],"graphs":[{"colorField":"color","fillAlphas":1,"id":"dailyAmGraph-1","lineColorField":"color","title":"آمار بازديد","type":"column","valueField":"c-1"},{"colorField":"color","fillAlphas":1,"id":"dailyAmGraph-2","lineColorField":"color","title":"ورودي آي پي","type":"column","valueField":"c-2"}],"guides":[],"valueAxes":[{"id":"dailyValueAxis-1","title":"تعداد"}],"allLabels":[],"balloon":{},"legend":{"enabled":!0,"useGraphSettings":!0},"responsive":{"enabled":!0},"dataProvider":chart_data,"listeners":[{"event":"init","method":function(event){var chart=event.chart;for(var x=0;x<chart.graphs.length;x++){var graph=chart.graphs[x];var graphSum=0;for(var i=0;i<chart.dataProvider.length;i++){graphSum+=chart.dataProvider[i][graph.valueField]}
if(graphSum==0)
{graph.visibleInLegend=!1;chart.hideGraph(graph)}}}}]});chart.addListener("rendered",zoomChart);zoomChart()}
function hourly_chart(chart_id,chart_data,nukeurl){chart=AmCharts.makeChart(chart_id,{"type":"serial","fontFamily":"Tahoma","marginRight":20,"marginLeft":50,"autoMarginOffset":0,"mouseWheelZoomEnabled":!0,"addClassNames":!0,"dataProvider":chart_data,"valueAxes":[{"axisAlpha":0,"dashLength":4,"position":"left","id":"hourlyValueAxis-1","title":"تعداد"}],"graphs":[{"id":"hourlyAmGraph-1","bulletSize":14,"customBullet":nukeurl+"modules/Statistics/includes/star.png?x","customBulletField":"customBullet","valueField":"c-1","title":"آمار بازدید","balloonText":"<span style='font-size:15px;'>[[value]]</span>",}],"marginTop":20,"marginBottom":20,"chartCursor":{"graphBulletSize":1.5,"zoomable":!0,"valueZoomable":!1,"cursorAlpha":0,"valueLineEnabled":!0,"valueLineBalloonEnabled":!0,"valueLineAlpha":0.2},"autoMargins":!1,"categoryField":"date","categoryAxis":{"axisAlpha":0,"gridAlpha":0,"inside":!1,"tickLength":0},"export":{"enabled":!0},"legend":{"enabled":!0,"useGraphSettings":!0},"responsive":{"enabled":!0},});chart.addListener("rendered",zoomChart);zoomChart()}
function pie_chart(chart_id,chart_data,title_field,value_field)
{var legend;AmCharts.ready(function(){chart=new AmCharts.AmPieChart();chart.dataProvider=chart_data;chart.titleField=title_field;chart.valueField=value_field;chart.outlineColor="#FFFFFF";chart.outlineAlpha=0.8;chart.outlineThickness=2;chart.labelsEnabled=!1;chart.balloonText="[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>";legend=new AmCharts.AmLegend();legend.align="center";legend.markerType="circle";legend.textClickEnabled=!0;legend.switchable=!0;legend.equalWidths=!0;legend.maxColumns=3;legend.valueWidth=80;chart.addLegend(legend,chart_id+"_legend");chart.depth3D=10;chart.angle=30;chart.responsive={"enabled":!0};chart.write(chart_id)})}
function zoomChart(){chart.zoomToIndexes(chart.dataProvider.length-26,chart.dataProvider.length-1)}