<?php

$rewrite_rule["article"] = array(
	"send-article/?$" => 'index.php?modname=Articles&op=send_article',
	"archive/all(/page/([0-9]{1,}+))?/?$" => 'index.php?modname=Articles&op=article_archive&page=$2&mode=all',
	"archive(/([0-9]{1,4}+)/([0-9]{1,2}+)/([^/]+)(/page/([0-9]{1,}+))?)?/?$" => 'index.php?modname=Articles&op=article_archive&year=$2&month=$3&month_l=$4&page=$6',
	"category/(.+)(/page/([0-9]{1,}+))?/?$" => 'index.php?modname=Articles&category=$1&page=$3',
	"category/?$" => 'index.php?modname=Articles&op=article_categories',
	"tags/([^/]+?)(/page/([0-9]{1,}+))?/?$" => 'index.php?modname=Articles&tags=$1&page=$3',
	"(most-visit|most-comment|most-rate)(/page/([0-9]{1,}+))?/?$" => 'index.php?modname=Articles&orderby=$1&page=$3',
	"([0-9]{4})/(([0-9]{1,2})/)?(([0-9]{1,2})/)?(most-visit|most-comment|most-rate)?/?(page/([0-9]{1,}+))?/?$" => 'index.php?modname=Articles&datetime=$1-$3-$5&orderby=$6&page=$8',
	"([^/]+)/(pdf|print|friend|report)?/?(comment-page-([0-9]{1,}+))?/?$" => 'index.php?modname=Articles&op=article_show&post_url=$1&mode=$2&page=$4',
	"page/([0-9]{1,}+)?/?$" => 'index.php?modname=Articles&page=$1',
	"(.+)/(([^/]+)/?)(pdf|print|friend|report)?/?(comment-page-([0-9]{1,}+))?/?$" => 'index.php?modname=Articles&op=article_show&args=$1&post_url=$3&mode=$4&page=$6',
);

$friendly_links = array(
	"index.php\?modname=Articles&category=(.+)&orderby=([^/]+)&page=([0-9]{1,}+)$" => 'category/$1/$2/page/$3/',
	"index.php\?modname=Articles&category=(.+)&orderby=([^/]+)$" => 'category/$1/$2/',
	"index.php\?modname=Articles&category=(.+)&page=([0-9]{1,}+)$" => 'category/$1/page/$2/',
	"index.php\?modname=Articles&category=(.+)$" => 'category/$1/',
	"index.php\?modname=Articles&tags=([^/]+)&page=([0-9]{1,}+)$" => 'tags/$1/page/$2/',
	"index.php\?modname=Articles&tags=([^/]+)$" => 'tags/$1/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&day=([0-9]{1,2})&orderby=([^/]+)&page=([0-9]{1,}+)$" => '$1/$2/$3/$4/page/$5/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&day=([0-9]{1,2})&orderby=([^/]+)$" => '$1/$2/$3/$4/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&day=([0-9]{1,2})&page=([0-9]{1,}+)$" => '$1/$2/$3/page/$4/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&day=([0-9]{1,2})$" => '$1/$2/$3/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&orderby=([^/]+)&page=([0-9]{1,}+)$" => '$1/$2/$3/page/$4/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&orderby=([^/]+)$" => '$1/$2/$3/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&page=([0-9]{1,}+)$" => '$1/$2/page/$3/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})$" => '$1/$2/',
	"index.php\?modname=Articles&year=([0-9]{4,})&orderby=([^/]+)&page=([0-9]{1,}+)$" => '$1/$2/page/$3/',
	"index.php\?modname=Articles&year=([0-9]{4,})&orderby=([^/]+)$" => '$1/$2/',
	"index.php\?modname=Articles&year=([0-9]{4,})&page=([0-9]{1,}+)$" => '$1/page/$2/',
	"index.php\?modname=Articles&year=([0-9]{4,})$" => '$1/',
	"index.php\?modname=Articles&orderby=([^/]+)&page=([0-9]{1,}+)$" => '$2/page/$2/',
	"index.php\?modname=Articles&orderby=([^/]+)$" => '$1/',
	"index.php\?modname=Articles&page=([0-9]{1,}+)$" => 'page/$1/',
	"index.php\?modname=Articles&category=(.+)&post_url=([^/]+)$" => '$1/$2/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&day=([0-9]{1,2})&post_url=([^/]+)&op=(pdf|print|friend|report)$" => '$1/$2/$3/$4/$5/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&day=([0-9]{1,2})&post_url=([^/]+)$" => '$1/$2/$3/$4/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&post_url=([^/]+)&op=(pdf|print|friend|report)$" => '$1/$2/$3/$4/',
	"index.php\?modname=Articles&year=([0-9]{4,})&month=([0-9]{1,2})&post_url=([^/]+)$" => '$1/$2/$3/',
	"index.php\?modname=Articles&year=([0-9]{4,})&post_url=([^/]+)&op=(pdf|print|friend|report)$" => '$1/$2/$3/',
	"index.php\?modname=Articles&year=([0-9]{4,})&post_url=([^/]+)$" => '$1/$2/',
	"index.php\?modname=Articles&sid=([0-9])&post_url=([^/]+)&op=(pdf|print|friend|report)$" => '$1/$2/$3/',
	"index.php\?modname=Articles&sid=([0-9])&post_url=([^/]+)$" => '$1/$2/',
	"index.php\?modname=Articles&post_url=([^/]+)&op=(pdf|print|friend|report)$" => '$1/$2/',
	"index.php\?modname=Articles&sid=([0-9])$" => '$1/',
    'index.php\?modname=Articles&op=article_categories$' => 'category/',
    'index.php\?modname=Articles&op=send_article$' => 'send-article/',
    'index.php\?modname=Articles&op=article_archive&year=([0-9]{1,4}+)&month=([0-9]{1,2}+)&month_l=([^/]+)&page=([0-9]{1,}+)$' => 'archive/$1/$2/$3/page/$4/',
    'index.php\?modname=Articles&op=article_archive&year=([0-9]{1,4}+)&month=([0-9]{1,2}+)&month_l=([^/]+)$' => 'archive/$1/$2/$3/',
    'index.php\?modname=Articles&op=article_archive&page=([0-9]{1,}+)$' => 'archive/all/page/$1/',
    'index.php\?modname=Articles&op=article_archive$' => 'archive/all/',
    'index.php\?modname=Articles&op=article_select_month$' => 'archive/',
	"index.php\?modname=Articles$" => '',
);

?>